/*
 * DvmaWalkAllModulesTest.kt
 *
 * Android-native "walk every module" driver for DVMA (Damn Vulnerable Mobile
 * App) using UiAutomator. Authorized security-training use only. This is a
 * reference copy; the wired-in copy CI compiles lives at
 * android/app/src/androidTest/kotlin/com/dvma/DvmaWalkAllModulesTest.kt.
 *
 * Why UiAutomator, not Espresso view matchers: DVMA is a Flutter app whose UI is
 * drawn to a single native canvas, so Espresso view matchers can't see
 * individual widgets. DVMA instruments each automatable widget in
 * `lib/core/test_ids.dart` with a `Semantics(identifier: id)` node, which
 * surfaces on Android as the element's resource-id in the accessibility tree.
 * UiAutomator reads that tree, so `By.res("<id>")` works.
 *
 * Staying in sync with the module list: the canonical list lives in
 * `automation/vuln_manifest.json` (generated by `tool/generate.dart`). A pure
 * JUnit/androidTest run can't easily read a repo file at runtime, so this test
 * discovers modules dynamically instead of hardcoding ids: it repeatedly scrolls
 * the home list and collects every element whose resource-id starts with the
 * `vuln_row_` prefix, then opens each. To pin an explicit list (e.g. to
 * guarantee coverage/order), copy the `id`s from vuln_manifest.json into
 * MODULE_IDS below and set USE_MANIFEST_LIST = true, re-running the generator
 * after adding modules. See automation/README.md for the androidTest
 * dependencies and run commands.
 */

package com.dvma

import android.content.Context
import android.content.Intent
import androidx.test.core.app.ApplicationProvider
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import androidx.test.uiautomator.By
import androidx.test.uiautomator.Direction
import androidx.test.uiautomator.UiDevice
import androidx.test.uiautomator.Until
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertTrue
import org.junit.After
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(AndroidJUnit4::class)
class DvmaWalkAllModulesTest {

    private lateinit var device: UiDevice
    private val pkg = BuildConfig.APPLICATION_ID

    // Stable id prefixes/ids mirror lib/core/test_ids.dart.
    private val disclaimerBannerId = "dvma_disclaimer_banner"
    private val searchFieldId = "dvma_search_field"
    private val expandAllId = "dvma_expand_all"
    private val clearSearchId = "dvma_clear_search"
    private val moduleManifestId = "dvma_module_manifest"
    private val rowIdPrefix = "vuln_row_"
    private val screenIdPrefix = "demo_screen_"
    private val actionIdPrefix = "demo_action_"
    private val evidenceIdPrefix = "evidence_"

    // Navigation mode this device used before the test, so @After can restore
    // it. We force 3-button navigation for the run (see forceThreeButtonNav).
    private var savedNavMode: String? = null

    @Before
    fun launchApp() {
        device = UiDevice.getInstance(InstrumentationRegistry.getInstrumentation())

        // CRITICAL (flawless-walk requirement): on gesture-navigation devices a
        // swipe that begins in the bottom system-gesture inset is swallowed by
        // the OS as a HOME / app-switcher gesture, which throws DVMA to the
        // background and blanks the walk. We (a) switch the device to 3-button
        // navigation for the duration of the test so there is no bottom-edge
        // home gesture, and (b) still keep every swipe inset from all edges
        // (see swipeInset) as defense in depth. The original mode is restored
        // in @After.
        savedNavMode = forceThreeButtonNav()

        device.pressHome()
        val context = ApplicationProvider.getApplicationContext<Context>()
        val intent = context.packageManager.getLaunchIntentForPackage(pkg)?.apply {
            addFlags(Intent.FLAG_ACTIVITY_CLEAR_TASK)
        }
        assertNotNull("No launch intent for $pkg - is DVMA installed?", intent)
        context.startActivity(intent)
        device.wait(Until.hasObject(By.pkg(pkg).depth(0)), LAUNCH_TIMEOUT)
    }

    @After
    fun restoreNav() {
        savedNavMode?.let { restoreNavMode(it) }
    }

    @Test
    fun walkEveryModule() {
        // Confirm the intentionally-vulnerable home index booted.
        val banner = device.wait(Until.findObject(By.res(disclaimerBannerId)), UI_TIMEOUT)
        assertNotNull("Disclaimer banner not found; home did not render", banner)

        val moduleIds = if (USE_MANIFEST_LIST) MODULE_IDS.toList() else discoverModuleIds()
        assertTrue("No vuln_row_* rows discovered", moduleIds.isNotEmpty())

        val failures = mutableListOf<String>()
        val noEvidence = mutableListOf<String>()
        var opened = 0
        var verified = 0

        for (id in moduleIds) {
            val rowId = "$rowIdPrefix$id"
            val screenId = "$screenIdPrefix$id"
            try {
                // Navigate BY SEARCH (never scroll to find a row): reach home,
                // type the id into the search field, then tap the single result
                // row. This is deterministic and never touches a screen edge -
                // the same technique the shell verify_all_modules.sh uses.
                openModuleBySearch(id, rowId)

                val screen = device.wait(Until.findObject(By.res(screenId)), UI_TIMEOUT)
                    ?: throw AssertionError("demo screen $screenId not visible")
                assertNotNull(screen)
                opened++

                // Exercise stateful controls first (flip switches, nudge
                // sliders) so a module that gates behavior on a control state is
                // covered in a non-default position before the action-taps fire.
                exerciseControls()

                // Trigger the vulnerable path: tap EVERY demo action on the
                // screen (vuln + secure + any extra triggers), so a module that
                // only records evidence on a non-first button still fires.
                val tapped = tapAllDemoActions()

                // VERIFY IT ACTUALLY DID SOMETHING: after triggering, at least
                // one evidence_* panel must be present on-device. Every module
                // renders an EvidencePanel, so a populated panel is the on-device
                // proof the vulnerable code path ran and produced an artifact.
                // Scroll-aware: the panel may be below the fold after tapping.
                val hasEvidence = findResScrolling(
                    java.util.regex.Pattern.compile("$evidenceIdPrefix.*"),
                )
                if (hasEvidence) {
                    verified++
                    println("DVMA-VERDICT: [$id] VERIFIED (tapped $tapped action(s), evidence panel present)")
                } else {
                    noEvidence.add(id)
                    println("DVMA-VERDICT: [$id] NO-EVIDENCE (tapped $tapped action(s), no evidence_* panel)")
                }

                // Capture evidence. UiDevice.takeScreenshot writes a PNG we can pull
                // from the device (see README for `adb pull`).
                val shot = java.io.File(screenshotDir(), "$id.png")
                device.takeScreenshot(shot)

                // Back to the home index for the next module.
                device.pressBack()
                device.wait(Until.hasObject(By.res(disclaimerBannerId)), UI_TIMEOUT)
            } catch (t: Throwable) {
                // Record the exception class too - a bare `.message` is null for
                // NPE/StaleObjectException and makes failures undebuggable.
                val detail = t.message ?: t.javaClass.simpleName
                failures.add("$id: $detail")
                println("DVMA-WALK-ERROR: [$id] ${t.javaClass.name}: ${t.message}")
                // Best-effort recovery to a known, searchable home state. Never
                // relies on gestures: relaunch DVMA via its launch intent.
                recoverToHome()
            }
        }

        println("DVMA walk complete: opened $opened/${moduleIds.size} modules, " +
            "$verified verified (evidence panel present), " +
            "${noEvidence.size} produced NO evidence, ${failures.size} failure(s).")
        if (noEvidence.isNotEmpty()) {
            println("DVMA modules with NO on-device evidence panel:")
            noEvidence.forEach { println("  - $it") }
        }
        failures.forEach { println("  - $it") }
        assertTrue("Some modules failed to open/navigate: $failures", failures.isEmpty())
    }

    /**
     * Scroll the home list, collecting every visible resource-id that starts with
     * `vuln_row_`, until a full screen adds no new ids. Returns bare module ids
     * (prefix stripped), in first-seen order.
     */
    private fun discoverModuleIds(): List<String> {
        // PRIMARY (fully dynamic, drift-proof): read the app's OWN runtime
        // manifest - the hidden `dvma_module_manifest` node whose label carries
        // the comma-separated enabled-module ids (VulnerabilityRegistry). On
        // Android the Flutter Semantics `label` surfaces as the node's
        // content-description.
        moduleIdsFromApp()?.let { ids ->
            if (ids.isNotEmpty()) {
                println("DVMA walk: using ${ids.size} module id(s) from the app's runtime manifest")
                expandAllCategories() // search results still need rows built
                return ids
            }
        }

        // The home index shows COLLAPSED category cards; individual vuln_row_*
        // elements only exist once categories are expanded. Tap "Expand all"
        // (identified by its content-description; it has no stable test id).
        expandAllCategories()

        val seen = LinkedHashSet<String>()
        var stableScreens = 0
        var iterations = 0

        while (stableScreens < 2 && iterations < MAX_SCROLLS) {
            iterations++
            val before = seen.size
            for (obj in device.findObjects(By.res(java.util.regex.Pattern.compile("$rowIdPrefix.*")))) {
                val res = obj.resourceName ?: continue
                if (res.startsWith(rowIdPrefix)) seen.add(res.removePrefix(rowIdPrefix))
            }
            stableScreens = if (seen.size == before) stableScreens + 1 else 0
            scrollList(Direction.DOWN)
        }

        // Scroll back to the top so the walk opens rows from the beginning.
        var guard = 0
        while (scrollList(Direction.UP) && guard++ < MAX_SCROLLS) { /* rewind */ }
        return seen.toList()
    }

    /**
     * Read the comma-separated enabled-module ids from the app's hidden
     * `dvma_module_manifest` node. The Flutter Semantics `label` surfaces as the
     * node's content-description on Android. Returns null if absent (older
     * build), so callers fall back to scroll-discovery.
     */
    private fun moduleIdsFromApp(): List<String>? {
        val node = device.wait(Until.findObject(By.res(moduleManifestId)), UI_TIMEOUT)
            ?: return null
        val csv = node.contentDescription ?: node.text ?: return null
        val ids = csv.split(",").map { it.trim() }.filter { it.isNotEmpty() }
        return ids.ifEmpty { null }
    }

    /**
     * Expand every category on the home index so `vuln_row_*` elements render.
     * The toggle's label is "Expand all" when collapsed and "Collapse all" when
     * already open, so we only tap when we see "Expand all".
     */
    private fun expandAllCategories() {
        device.wait(Until.hasObject(By.res(disclaimerBannerId)), UI_TIMEOUT)
        // Prefer the stable test id; fall back to the localized content-desc.
        val expand = device.wait(Until.findObject(By.res(expandAllId)), UI_TIMEOUT)
            ?: device.wait(Until.findObject(By.desc("Expand all")), UI_TIMEOUT)
        expand?.click()
        device.waitForIdle()
    }

    /**
     * True if any element matching [pattern] is present, scrolling the module
     * screen to reveal it if needed (evidence panels can be above or below the
     * action buttons). First checks the current view, then rewinds up, then
     * scans downward.
     */
    private fun findResScrolling(pattern: java.util.regex.Pattern): Boolean {
        if (device.wait(Until.findObject(By.res(pattern)), EVIDENCE_TIMEOUT) != null) return true
        var guard = 0
        while (scrollList(Direction.UP) && guard++ < MAX_SCROLLS) {
            if (device.findObject(By.res(pattern)) != null) return true
        }
        guard = 0
        while (scrollList(Direction.DOWN) && guard++ < MAX_SCROLLS) {
            if (device.findObject(By.res(pattern)) != null) return true
        }
        return device.findObject(By.res(pattern)) != null
    }

    /**
     * Scroll the list one page in [dir] using an EDGE-SAFE swipe.
     *
     * We deliberately do NOT use `UiObject2.scroll()` / `UiScrollable`: those
     * gesture inside the scrollable's bounds, which on a full-screen Flutter
     * list reach the very bottom of the display. On a gesture-navigation device
     * a swipe that starts in the bottom system-gesture inset is consumed by the
     * OS as a HOME / app-switcher gesture (it backgrounds DVMA and blanks the
     * walk). Instead we swipe between two points kept well inside a central band
     * of the screen - insetting from ALL edges - so the gesture is always
     * delivered to the app, never the system. Returns true if the accessibility
     * tree changed (content moved), so callers can stop at the ends of the list.
     */
    private fun scrollList(dir: Direction): Boolean {
        val w = device.displayWidth
        val h = device.displayHeight
        val x = w / 2
        // Keep both endpoints inside [topInset, bottomInset]; the bottom inset
        // is generous so we never enter the bottom gesture zone.
        val topY = (h * TOP_INSET_FRAC).toInt()
        val bottomY = (h * BOTTOM_INSET_FRAC).toInt()
        val before = treeSignature()
        when (dir) {
            // Swipe UP (finger bottom->top) scrolls the list DOWN (reveals more).
            Direction.DOWN -> device.swipe(x, bottomY, x, topY, SWIPE_STEPS)
            // Swipe DOWN (finger top->bottom) scrolls the list UP (rewind).
            Direction.UP -> device.swipe(x, topY, x, bottomY, SWIPE_STEPS)
            else -> return false
        }
        device.waitForIdle()
        // Content moved iff the visible tree changed.
        return treeSignature() != before
    }

    /**
     * A cheap signature of what's currently on screen (the set of visible
     * vuln_row_/demo_action_/evidence_ resource-ids), used to detect whether a
     * swipe actually moved content so we can stop at list ends.
     */
    private fun treeSignature(): String {
        val ids = device.findObjects(
            By.res(java.util.regex.Pattern.compile("(vuln_row_|demo_action_|evidence_).*")),
        ).mapNotNull { runCatching { it.resourceName }.getOrNull() }
        return ids.sorted().joinToString(",")
    }

    /**
     * Flip every Switch and nudge every SeekBar (slider) on the current screen
     * so a module that gates behavior on a control state is exercised in a
     * non-default position before the action-taps fire the vulnerable path.
     * Best-effort and resilient: failures here never abort the walk.
     */
    private fun exerciseControls() {
        for (sw in device.findObjects(By.clazz("android.widget.Switch"))) {
            runCatching { sw.click() }
            device.waitForIdle()
        }
        for (sb in device.findObjects(By.clazz("android.widget.SeekBar"))) {
            // Swipe the seekbar toward its high end so range-driven modules run
            // with a larger value; a horizontal drag inside its own bounds.
            runCatching {
                val b = sb.visibleBounds
                device.swipe(
                    b.left + (b.width() * 0.15).toInt(), b.centerY(),
                    b.left + (b.width() * 0.85).toInt(), b.centerY(),
                    10,
                )
            }
            device.waitForIdle()
        }
    }

    /**
     * Tap EVERY `demo_action_*` button on the current screen, top to bottom.
     * Returns the number tapped. Some modules gate their evidence on a specific
     * (non-first) button, or split vuln/secure across buttons, so we fire them
     * all. After each tap we wait for idle and scroll to reveal any buttons
     * below the fold.
     */
    private fun tapAllDemoActions(): Int {
        val tappedCenters = HashSet<String>()
        var guard = 0
        while (guard++ < MAX_SCROLLS) {
            val actions = device.findObjects(
                By.res(java.util.regex.Pattern.compile("$actionIdPrefix.*")),
            )
            var tappedNew = false
            for (a in actions) {
                // Dedupe by on-screen center so we don't re-tap the same button
                // across scroll iterations. Guard the WHOLE body: a prior tap can
                // re-render the list and stale a later handle, so even reading
                // `visibleCenter` can throw StaleObjectException.
                runCatching {
                    val c = a.visibleCenter
                    val key = "${c.x},${c.y}"
                    if (tappedCenters.add(key)) {
                        a.click()
                        device.waitForIdle()
                        tappedNew = true
                    }
                }
            }
            // Try to reveal more actions further down; stop when nothing scrolls
            // and we tapped nothing new this pass.
            val scrolled = scrollList(Direction.DOWN)
            if (!scrolled && !tappedNew) break
        }
        return tappedCenters.size
    }

    /**
     * On-device directory for screenshots. Files land in the app-external test
     * files dir; pull them with `adb pull` (see README).
     */
    private fun screenshotDir(): java.io.File {
        val ctx = InstrumentationRegistry.getInstrumentation().targetContext
        val dir = java.io.File(ctx.getExternalFilesDir(null), "dvma-artifacts")
        dir.mkdirs()
        return dir
    }

    // Search-based navigation (edge-free)

    /**
     * Open a module BY SEARCH: reach a clean home, focus the search field,
     * clear any leftover query, type this module's id, then tap the single
     * result row. No scrolling, so it never touches a screen edge. Mirrors the
     * deterministic technique in automation/scripts/verify_all_modules.sh.
     */
    private fun openModuleBySearch(id: String, rowId: String) {
        // Ensure we're on a searchable home (the search field is present).
        if (device.wait(Until.findObject(By.res(searchFieldId)), UI_TIMEOUT) == null) {
            recoverToHome()
        }
        val field = device.wait(Until.findObject(By.res(searchFieldId)), UI_TIMEOUT)
            ?: throw AssertionError("search field ($searchFieldId) not found")
        field.click()
        device.waitForIdle()
        clearSearch()
        // Type the id and confirm the target row appears.
        setSearchText(id)
        val row = device.wait(Until.findObject(By.res(rowId)), UI_TIMEOUT)
            ?: throw AssertionError("row $rowId not found after searching \"$id\"")
        // The filtered Flutter list can re-render between find and click, which
        // invalidates `row` (StaleObjectException). Let the list settle, then
        // click a freshly-queried handle, retrying once on staleness.
        device.waitForIdle()
        try {
            (device.findObject(By.res(rowId)) ?: row).click()
        } catch (_: androidx.test.uiautomator.StaleObjectException) {
            val fresh = device.wait(Until.findObject(By.res(rowId)), UI_TIMEOUT)
                ?: throw AssertionError("row $rowId went stale and did not reappear")
            fresh.click()
        }
    }

    /** Clear the search field via its "Clear search" affordance, falling back to
     *  select-all + delete. Verifies the field ends up empty. */
    private fun clearSearch() {
        // The app shows a "Clear search" (X) control only while the query is
        // non-empty; tap it when present. Prefer the stable test id.
        val clear = device.findObject(By.res(clearSearchId))
            ?: device.findObject(By.desc("Clear search"))
        if (clear != null) {
            runCatching { clear.click() }
            device.waitForIdle()
        }
        // Fallback: if an editable field still holds text, delete it.
        val edit = device.findObject(By.clazz("android.widget.EditText"))
        val text = edit?.text ?: ""
        if (text.isNotEmpty()) {
            edit?.let { runCatching { it.text = "" } }
            device.waitForIdle()
        }
    }

    /** Type [q] into the focused search field and confirm it registered. */
    private fun setSearchText(q: String) {
        val edit = device.wait(
            Until.findObject(By.clazz("android.widget.EditText")),
            UI_TIMEOUT,
        ) ?: device.findObject(By.res(searchFieldId))
        edit?.let { runCatching { it.text = q } }
        device.waitForIdle()
    }

    /**
     * Return DVMA to a clean, searchable home WITHOUT any gesture: relaunch it
     * via its launch intent (CLEAR_TASK), then wait for the search field. Used
     * for per-error recovery so one stray state can't cascade.
     */
    private fun recoverToHome() {
        val context = ApplicationProvider.getApplicationContext<Context>()
        val intent = context.packageManager.getLaunchIntentForPackage(pkg)?.apply {
            addFlags(Intent.FLAG_ACTIVITY_CLEAR_TASK or Intent.FLAG_ACTIVITY_NEW_TASK)
        }
        if (intent != null) {
            context.startActivity(intent)
            device.wait(Until.hasObject(By.pkg(pkg).depth(0)), LAUNCH_TIMEOUT)
        }
        device.wait(Until.hasObject(By.res(searchFieldId)), UI_TIMEOUT)
    }

    // Navigation-mode control (kills the bottom-edge home gesture)

    /**
     * Force 3-button navigation for the test run so there is NO bottom-edge
     * gesture the OS can steal from an in-app swipe. Returns the previous mode
     * so [restoreNavMode] can put it back, or null if it couldn't be changed
     * (the edge-safe swipe insets still protect the walk in that case).
     */
    private fun forceThreeButtonNav(): String? {
        val prev = shell("cmd overlay list android 2>/dev/null")
        // Enable the 3-button-nav overlay; disable the gestural ones.
        shell("cmd overlay enable com.android.internal.systemui.navbar.threebutton")
        shell("cmd overlay disable com.android.internal.systemui.navbar.gestural")
        device.waitForIdle()
        return prev
    }

    /** Best-effort restore of the pre-test navigation mode. */
    private fun restoreNavMode(@Suppress("UNUSED_PARAMETER") saved: String) {
        // Re-enable gesture nav (the common device default); harmless if the
        // device was already on 3-button.
        shell("cmd overlay enable com.android.internal.systemui.navbar.gestural")
        shell("cmd overlay disable com.android.internal.systemui.navbar.threebutton")
        device.waitForIdle()
    }

    /** Run a shell command via the instrumentation and return its output. */
    private fun shell(cmd: String): String =
        runCatching { device.executeShellCommand(cmd) }.getOrDefault("")

    private companion object {
        const val LAUNCH_TIMEOUT = 30_000L
        const val UI_TIMEOUT = 15_000L
        const val EVIDENCE_TIMEOUT = 6_000L
        const val MAX_SCROLLS = 40

        // Edge-safe swipe geometry: both swipe endpoints stay within
        // [TOP_INSET_FRAC, BOTTOM_INSET_FRAC] of the display height, so a swipe
        // never begins/ends in the top status or bottom system-gesture inset.
        const val TOP_INSET_FRAC = 0.25
        const val BOTTOM_INSET_FRAC = 0.70
        const val SWIPE_STEPS = 20

        // Set true and populate to walk an explicit, ordered list instead of
        // dynamically discovering rows. Copy `id`s from automation/vuln_manifest.json.
        const val USE_MANIFEST_LIST = false
        val MODULE_IDS = arrayOf<String>(
            // "insecure_local_storage",
            // "keychain_keystore_misuse",
            // ... (see automation/vuln_manifest.json for the full list)
        )
    }
}
