// GENERATED by tool/generate.dart. DO NOT EDIT BY HAND.
// Maps each vulnerability id to its module screen builder.
//
// ignore_for_file: lines_longer_than_80_chars

import 'package:flutter/material.dart';

import '../modules/agentic/agent_memory_poisoning/agent_memory_poisoning_screen.dart';
import '../modules/agentic/agent_recovery_loop_weaponization/agent_recovery_loop_weaponization_screen.dart';
import '../modules/agentic/agent_state_toctou_swap/agent_state_toctou_swap_screen.dart';
import '../modules/agentic/agent_tool_confused_deputy/agent_tool_confused_deputy_screen.dart';
import '../modules/agentic/gui_agent_action_rebinding/gui_agent_action_rebinding_screen.dart';
import '../modules/agentic/insecure_inter_agent_comms/insecure_inter_agent_comms_screen.dart';
import '../modules/agentic/mcp_capability_attestation_absent/mcp_capability_attestation_absent_screen.dart';
import '../modules/agentic/mcp_open_url_arbitrary_intent/mcp_open_url_arbitrary_intent_screen.dart';
import '../modules/agentic/mcp_tool_poisoning/mcp_tool_poisoning_screen.dart';
import '../modules/ai_ml/excessive_agent_agency/excessive_agent_agency_screen.dart';
import '../modules/ai_ml/hardcoded_llm_api_keys/hardcoded_llm_api_keys_screen.dart';
import '../modules/ai_ml/hidden_context_exposure/hidden_context_exposure_screen.dart';
import '../modules/ai_ml/insecure_ondevice_model_storage/insecure_ondevice_model_storage_screen.dart';
import '../modules/ai_ml/insecure_output_handling/insecure_output_handling_screen.dart';
import '../modules/ai_ml/ondevice_model_extraction/ondevice_model_extraction_screen.dart';
import '../modules/ai_ml/prompt_injection_direct/prompt_injection_direct_screen.dart';
import '../modules/ai_ml/prompt_injection_indirect/prompt_injection_indirect_screen.dart';
import '../modules/ai_ml/rag_vector_store_poisoning/rag_vector_store_poisoning_screen.dart';
import '../modules/ai_ml/system_prompt_leakage/system_prompt_leakage_screen.dart';
import '../modules/ai_ml/unbounded_ai_resource_consumption/unbounded_ai_resource_consumption_screen.dart';
import '../modules/ai_ml/unicode_invisible_prompt_injection/unicode_invisible_prompt_injection_screen.dart';
import '../modules/ai_ml/unverified_model_supply_chain/unverified_model_supply_chain_screen.dart';
import '../modules/ai_mobile/accessibility_tree_prompt_injection/accessibility_tree_prompt_injection_screen.dart';
import '../modules/ai_mobile/ai_output_command_tool_injection/ai_output_command_tool_injection_screen.dart';
import '../modules/ai_mobile/ai_output_to_intent_url/ai_output_to_intent_url_screen.dart';
import '../modules/ai_mobile/ai_output_to_webview_xss/ai_output_to_webview_xss_screen.dart';
import '../modules/ai_mobile/untrusted_mobile_input_to_llm/untrusted_mobile_input_to_llm_screen.dart';
import '../modules/auth/biometric_authorization_not_bound/biometric_authorization_not_bound_screen.dart';
import '../modules/auth/client_side_only_authorization/client_side_only_authorization_screen.dart';
import '../modules/auth/credential_provider_release_authorization/credential_provider_release_authorization_screen.dart';
import '../modules/auth/cross_app_otp_credential_leak/cross_app_otp_credential_leak_screen.dart';
import '../modules/auth/deeplink_authentication_bypass/deeplink_authentication_bypass_screen.dart';
import '../modules/auth/developer_backdoor/developer_backdoor_screen.dart';
import '../modules/auth/identity_credential_presentation_binding/identity_credential_presentation_binding_screen.dart';
import '../modules/auth/insecure_biometric_prompt/insecure_biometric_prompt_screen.dart';
import '../modules/auth/insecure_credential_manager/insecure_credential_manager_screen.dart';
import '../modules/auth/insecure_password_reset_token/insecure_password_reset_token_screen.dart';
import '../modules/auth/jwt_vulnerabilities/jwt_vulnerabilities_screen.dart';
import '../modules/auth/multi_account_isolation_failure/multi_account_isolation_failure_screen.dart';
import '../modules/auth/oauth_misconfiguration/oauth_misconfiguration_screen.dart';
import '../modules/auth/passkey_assertion_replay_signcount/passkey_assertion_replay_signcount_screen.dart';
import '../modules/auth/passkey_challenge_reuse/passkey_challenge_reuse_screen.dart';
import '../modules/auth/passkey_credential_exfiltration/passkey_credential_exfiltration_screen.dart';
import '../modules/auth/passkey_credential_management_authz/passkey_credential_management_authz_screen.dart';
import '../modules/auth/passkey_fallback_downgrade/passkey_fallback_downgrade_screen.dart';
import '../modules/auth/passkey_origin_binding_bypass/passkey_origin_binding_bypass_screen.dart';
import '../modules/auth/passkey_session_fixation/passkey_session_fixation_screen.dart';
import '../modules/auth/passkey_stepup_auth_bypass/passkey_stepup_auth_bypass_screen.dart';
import '../modules/auth/passkey_thirdparty_pairing_authz/passkey_thirdparty_pairing_authz_screen.dart';
import '../modules/auth/passkey_user_verification_bypass/passkey_user_verification_bypass_screen.dart';
import '../modules/auth/passkey_weak_attestation/passkey_weak_attestation_screen.dart';
import '../modules/auth/username_enumeration/username_enumeration_screen.dart';
import '../modules/auth/weak_password_policy/weak_password_policy_screen.dart';
import '../modules/auth/weak_session_management/weak_session_management_screen.dart';
import '../modules/code_quality/debuggable_release_build/debuggable_release_build_screen.dart';
import '../modules/code_quality/native_code_memory_bugs/native_code_memory_bugs_screen.dart';
import '../modules/code_quality/no_obfuscation/no_obfuscation_screen.dart';
import '../modules/code_quality/verbose_error_handling/verbose_error_handling_screen.dart';
import '../modules/code_quality/vulnerable_dependencies/vulnerable_dependencies_screen.dart';
import '../modules/crypto/custom_crypto_implementation/custom_crypto_implementation_screen.dart';
import '../modules/crypto/device_secure_lock_not_enforced/device_secure_lock_not_enforced_screen.dart';
import '../modules/crypto/hardcoded_keys_ivs/hardcoded_keys_ivs_screen.dart';
import '../modules/crypto/improper_mac_verification/improper_mac_verification_screen.dart';
import '../modules/crypto/improper_signature_verification/improper_signature_verification_screen.dart';
import '../modules/crypto/insecure_random/insecure_random_screen.dart';
import '../modules/crypto/rsa_no_oaep_padding/rsa_no_oaep_padding_screen.dart';
import '../modules/crypto/unauthenticated_encryption_malleable_ciphertext/unauthenticated_encryption_malleable_ciphertext_screen.dart';
import '../modules/crypto/weak_algorithms/weak_algorithms_screen.dart';
import '../modules/crypto/weak_key_derivation/weak_key_derivation_screen.dart';
import '../modules/input_validation/deeplink_regex_dos/deeplink_regex_dos_screen.dart';
import '../modules/input_validation/protected_data_access_via_input_validation/protected_data_access_via_input_validation_screen.dart';
import '../modules/input_validation/unsafe_deserialization/unsafe_deserialization_screen.dart';
import '../modules/input_validation/unsafe_media_decoding/unsafe_media_decoding_screen.dart';
import '../modules/input_validation/unvalidated_intent_extras/unvalidated_intent_extras_screen.dart';
import '../modules/native_bridge/crossorigin_iframe_to_native_bridge/crossorigin_iframe_to_native_bridge_screen.dart';
import '../modules/native_bridge/embedded_miniapp_secret_exposure/embedded_miniapp_secret_exposure_screen.dart';
import '../modules/native_bridge/exported_broadcast_receiver_spoof/exported_broadcast_receiver_spoof_screen.dart';
import '../modules/native_bridge/js_bridge_callback_id_injection/js_bridge_callback_id_injection_screen.dart';
import '../modules/native_bridge/js_bridge_exposes_privileged_api/js_bridge_exposes_privileged_api_screen.dart';
import '../modules/native_bridge/provider_metadata_to_filesystem_traversal/provider_metadata_to_filesystem_traversal_screen.dart';
import '../modules/native_bridge/qr_nfc_to_privileged_action/qr_nfc_to_privileged_action_screen.dart';
import '../modules/native_bridge/shared_webview_miniapp_isolation/shared_webview_miniapp_isolation_screen.dart';
import '../modules/native_bridge/webview_cleartext_mixed_content_downgrade/webview_cleartext_mixed_content_downgrade_screen.dart';
import '../modules/native_bridge/webview_js_injection_ssl_bypass/webview_js_injection_ssl_bypass_screen.dart';
import '../modules/native_bridge/webview_origin_confusion_ipc/webview_origin_confusion_ipc_screen.dart';
import '../modules/native_bridge/webview_remote_debugging_enabled/webview_remote_debugging_enabled_screen.dart';
import '../modules/native_bridge/webview_safe_browsing_disabled/webview_safe_browsing_disabled_screen.dart';
import '../modules/native_bridge/webview_sop_csp_disabled/webview_sop_csp_disabled_screen.dart';
import '../modules/native_bridge/webview_url_loading_policy_confusion/webview_url_loading_policy_confusion_screen.dart';
import '../modules/network/accept_all_trust_manager/accept_all_trust_manager_screen.dart';
import '../modules/network/cleartext_traffic_allowed/cleartext_traffic_allowed_screen.dart';
import '../modules/network/insecure_webview_networking/insecure_webview_networking_screen.dart';
import '../modules/network/ssl_pinning_bypass/ssl_pinning_bypass_screen.dart';
import '../modules/network/weak_tls_config/weak_tls_config_screen.dart';
import '../modules/platform/accessibility_service_privilege_abuse/accessibility_service_privilege_abuse_screen.dart';
import '../modules/platform/activity_alias_exposure/activity_alias_exposure_screen.dart';
import '../modules/platform/activity_task_stack_hijacking/activity_task_stack_hijacking_screen.dart';
import '../modules/platform/android_capability_composition_chain/android_capability_composition_chain_screen.dart';
import '../modules/platform/app_clip_invocation_injection/app_clip_invocation_injection_screen.dart';
import '../modules/platform/app_intent_parameter_authorization/app_intent_parameter_authorization_screen.dart';
import '../modules/platform/authorization_by_mutable_resource_state/authorization_by_mutable_resource_state_screen.dart';
import '../modules/platform/background_activity_launch_abuse/background_activity_launch_abuse_screen.dart';
import '../modules/platform/clipboard_to_privileged_action_injection/clipboard_to_privileged_action_injection_screen.dart';
import '../modules/platform/clipboard_unauthorized_write_integrity/clipboard_unauthorized_write_integrity_screen.dart';
import '../modules/platform/clipdata_uri_grant_leakage/clipdata_uri_grant_leakage_screen.dart';
import '../modules/platform/confused_deputy_intent_validation/confused_deputy_intent_validation_screen.dart';
import '../modules/platform/contacts_provider_blind_sqli_oracle/contacts_provider_blind_sqli_oracle_screen.dart';
import '../modules/platform/content_provider_sql_injection/content_provider_sql_injection_screen.dart';
import '../modules/platform/content_uri_resolver_confused_deputy/content_uri_resolver_confused_deputy_screen.dart';
import '../modules/platform/contentprovider_filename_path_traversal/contentprovider_filename_path_traversal_screen.dart';
import '../modules/platform/cross_app_scripting/cross_app_scripting_screen.dart';
import '../modules/platform/cross_profile_data_capability_leakage/cross_profile_data_capability_leakage_screen.dart';
import '../modules/platform/custom_signature_permission_squatting/custom_signature_permission_squatting_screen.dart';
import '../modules/platform/custom_url_scheme_authorization/custom_url_scheme_authorization_screen.dart';
import '../modules/platform/deeplink_to_webview_navigation/deeplink_to_webview_navigation_screen.dart';
import '../modules/platform/deeplink_url_scheme_hijack/deeplink_url_scheme_hijack_screen.dart';
import '../modules/platform/default_role_holder_confusion/default_role_holder_confusion_screen.dart';
import '../modules/platform/document_picker_trusted_file_confusion/document_picker_trusted_file_confusion_screen.dart';
import '../modules/platform/dynamic_broadcast_receiver_exposure/dynamic_broadcast_receiver_exposure_screen.dart';
import '../modules/platform/dynamic_code_loading_rce/dynamic_code_loading_rce_screen.dart';
import '../modules/platform/exported_android_components/exported_android_components_screen.dart';
import '../modules/platform/exported_component_arbitrary_url_activity/exported_component_arbitrary_url_activity_screen.dart';
import '../modules/platform/exported_component_state_manipulation/exported_component_state_manipulation_screen.dart';
import '../modules/platform/file_descriptor_capability_leakage/file_descriptor_capability_leakage_screen.dart';
import '../modules/platform/fileprovider_path_traversal/fileprovider_path_traversal_screen.dart';
import '../modules/platform/grant_uri_permission_abuse/grant_uri_permission_abuse_screen.dart';
import '../modules/platform/handoff_useractivity_injection/handoff_useractivity_injection_screen.dart';
import '../modules/platform/implicit_intent_sensitive_data/implicit_intent_sensitive_data_screen.dart';
import '../modules/platform/inapp_browser_ui_spoofing/inapp_browser_ui_spoofing_screen.dart';
import '../modules/platform/incoming_call_metadata_missing_authorization/incoming_call_metadata_missing_authorization_screen.dart';
import '../modules/platform/insecure_webview/insecure_webview_screen.dart';
import '../modules/platform/intent_arg_injection_rce/intent_arg_injection_rce_screen.dart';
import '../modules/platform/intent_redirection/intent_redirection_screen.dart';
import '../modules/platform/ios_capability_composition_chain/ios_capability_composition_chain_screen.dart';
import '../modules/platform/missing_flag_secure/missing_flag_secure_screen.dart';
import '../modules/platform/notification_action_authorization_bypass/notification_action_authorization_bypass_screen.dart';
import '../modules/platform/notification_listener_authorization_bypass/notification_listener_authorization_bypass_screen.dart';
import '../modules/platform/ordered_broadcast_result_injection/ordered_broadcast_result_injection_screen.dart';
import '../modules/platform/over_privileged_permissions/over_privileged_permissions_screen.dart';
import '../modules/platform/overlay_phishing/overlay_phishing_screen.dart';
import '../modules/platform/pending_intent_hijacking/pending_intent_hijacking_screen.dart';
import '../modules/platform/pendingintent_provenance_confusion/pendingintent_provenance_confusion_screen.dart';
import '../modules/platform/persistable_uri_grant_abuse/persistable_uri_grant_abuse_screen.dart';
import '../modules/platform/photo_picker_over_access/photo_picker_over_access_screen.dart';
import '../modules/platform/platform_version_security_fallback/platform_version_security_fallback_screen.dart';
import '../modules/platform/predictive_back_leakage/predictive_back_leakage_screen.dart';
import '../modules/platform/privileged_service_binding_exposure/privileged_service_binding_exposure_screen.dart';
import '../modules/platform/proximity_transfer_unsafe_parsing/proximity_transfer_unsafe_parsing_screen.dart';
import '../modules/platform/push_notification_leakage/push_notification_leakage_screen.dart';
import '../modules/platform/qr_code_injection/qr_code_injection_screen.dart';
import '../modules/platform/qr_url_no_validation/qr_url_no_validation_screen.dart';
import '../modules/platform/remoteviews_widget_action_injection/remoteviews_widget_action_injection_screen.dart';
import '../modules/platform/shortcuts_path_symlink_sandbox_escape/shortcuts_path_symlink_sandbox_escape_screen.dart';
import '../modules/platform/ssrf_url_media_handler/ssrf_url_media_handler_screen.dart';
import '../modules/platform/system_surface_privileged_appintent_exposure/system_surface_privileged_appintent_exposure_screen.dart';
import '../modules/platform/tapjacking/tapjacking_screen.dart';
import '../modules/platform/telephony_capability_abuse/telephony_capability_abuse_screen.dart';
import '../modules/platform/unauthenticated_local_loopback_service/unauthenticated_local_loopback_service_screen.dart';
import '../modules/platform/universal_link_aasa_confusion/universal_link_aasa_confusion_screen.dart';
import '../modules/platform/wkwebview_untrusted_url_local_file/wkwebview_untrusted_url_local_file_screen.dart';
import '../modules/platform/zero_click_call_media_parse_sink/zero_click_call_media_parse_sink_screen.dart';
import '../modules/platform/zip_path_traversal/zip_path_traversal_screen.dart';
import '../modules/privacy/assistant_locked_device_capability_abuse/assistant_locked_device_capability_abuse_screen.dart';
import '../modules/privacy/cross_app_browser_history_access/cross_app_browser_history_access_screen.dart';
import '../modules/privacy/installed_app_enumeration/installed_app_enumeration_screen.dart';
import '../modules/privacy/lock_state_confusion_data_exposure/lock_state_confusion_data_exposure_screen.dart';
import '../modules/privacy/missing_consent_before_data_access/missing_consent_before_data_access_screen.dart';
import '../modules/privacy/no_tracking_transparency_prompt/no_tracking_transparency_prompt_screen.dart';
import '../modules/privacy/notification_alternate_surface_disclosure/notification_alternate_surface_disclosure_screen.dart';
import '../modules/privacy/pii_in_analytics_events/pii_in_analytics_events_screen.dart';
import '../modules/privacy/privacy_control_alternate_path_bypass/privacy_control_alternate_path_bypass_screen.dart';
import '../modules/resilience/anti_debugging_bypass/anti_debugging_bypass_screen.dart';
import '../modules/resilience/anti_tampering_integrity_bypass/anti_tampering_integrity_bypass_screen.dart';
import '../modules/resilience/app_attestation_absent/app_attestation_absent_screen.dart';
import '../modules/resilience/device_attestation_absent/device_attestation_absent_screen.dart';
import '../modules/resilience/emulator_detection_bypass/emulator_detection_bypass_screen.dart';
import '../modules/resilience/frida_detection_bypass/frida_detection_bypass_screen.dart';
import '../modules/resilience/malware_detection_absent/malware_detection_absent_screen.dart';
import '../modules/resilience/root_jailbreak_detection_bypass/root_jailbreak_detection_bypass_screen.dart';
import '../modules/resilience/toctou_race_condition/toctou_race_condition_screen.dart';
import '../modules/resilience/virtualization_detection_absent/virtualization_detection_absent_screen.dart';
import '../modules/storage/auth_state_rollback_restore/auth_state_rollback_restore_screen.dart';
import '../modules/storage/backup_archive_integrity_tampering/backup_archive_integrity_tampering_screen.dart';
import '../modules/storage/clipboard_leakage/clipboard_leakage_screen.dart';
import '../modules/storage/insecure_backups/insecure_backups_screen.dart';
import '../modules/storage/insecure_local_storage/insecure_local_storage_screen.dart';
import '../modules/storage/insecure_sdcard_external_storage/insecure_sdcard_external_storage_screen.dart';
import '../modules/storage/keyboard_cache_autofill_leakage/keyboard_cache_autofill_leakage_screen.dart';
import '../modules/storage/keychain_access_group_authorization_confusion/keychain_access_group_authorization_confusion_screen.dart';
import '../modules/storage/keychain_keystore_misuse/keychain_keystore_misuse_screen.dart';
import '../modules/storage/keychain_state_integrity_manipulation/keychain_state_integrity_manipulation_screen.dart';
import '../modules/storage/local_security_state_integrity_tampering/local_security_state_integrity_tampering_screen.dart';
import '../modules/storage/screenshot_taskswitcher_leakage/screenshot_taskswitcher_leakage_screen.dart';
import '../modules/storage/sensitive_data_in_crash_reports/sensitive_data_in_crash_reports_screen.dart';
import '../modules/storage/sensitive_data_in_logs/sensitive_data_in_logs_screen.dart';
import '../modules/storage/sensitive_data_in_memory/sensitive_data_in_memory_screen.dart';
import '../modules/storage/temp_file_leftovers/temp_file_leftovers_screen.dart';
import '../modules/storage/third_party_sdk_data_leakage/third_party_sdk_data_leakage_screen.dart';
import '../modules/supply_chain/dependency_confusion/dependency_confusion_screen.dart';
import '../modules/supply_chain/insecure_firebase_cloud_config/insecure_firebase_cloud_config_screen.dart';
import '../modules/supply_chain/malicious_third_party_sdk/malicious_third_party_sdk_screen.dart';
import '../modules/supply_chain/sbom_missing_or_stale/sbom_missing_or_stale_screen.dart';
import '../modules/supply_chain/sdk_exported_component_redirection/sdk_exported_component_redirection_screen.dart';
import '../modules/supply_chain/silent_sdk_auto_update/silent_sdk_auto_update_screen.dart';
import '../modules/supply_chain/typosquatted_dependency/typosquatted_dependency_screen.dart';
import '../modules/supply_chain/unsigned_unverified_build_artifact/unsigned_unverified_build_artifact_screen.dart';
import '../modules/system_provider/app_group_shared_container_amplification/app_group_shared_container_amplification_screen.dart';
import '../modules/system_provider/assist_screen_context_ai_exposure/assist_screen_context_ai_exposure_screen.dart';
import '../modules/system_provider/companion_device_pairing_confusion/companion_device_pairing_confusion_screen.dart';
import '../modules/system_provider/custom_keyboard_input_interception/custom_keyboard_input_interception_screen.dart';
import '../modules/system_provider/device_policy_mdm_capability_abuse/device_policy_mdm_capability_abuse_screen.dart';
import '../modules/system_provider/extension_activation_input_confusion/extension_activation_input_confusion_screen.dart';
import '../modules/system_provider/lockscreen_control_action_authorization/lockscreen_control_action_authorization_screen.dart';
import '../modules/system_provider/mediaprojection_screencapture_authorization_bypass/mediaprojection_screencapture_authorization_bypass_screen.dart';
import '../modules/system_provider/notification_intelligence_ai_processing/notification_intelligence_ai_processing_screen.dart';
import '../modules/system_provider/privileged_input_provider_injection/privileged_input_provider_injection_screen.dart';
import '../modules/system_provider/privileged_provider_activation_abuse/privileged_provider_activation_abuse_screen.dart';
import '../modules/system_provider/vpn_provider_trust_anchor_abuse/vpn_provider_trust_anchor_abuse_screen.dart';

typedef ScreenBuilder = Widget Function(BuildContext context);

/// Routes a vulnerability id to the widget that demonstrates it.
class ModuleRouter {
  ModuleRouter._();

  static const Map<String, ScreenBuilder> _screens = {
    'clipboard_leakage': _buildClipboardLeakageScreen,
    'insecure_backups': _buildInsecureBackupsScreen,
    'insecure_local_storage': _buildInsecureLocalStorageScreen,
    'insecure_sdcard_external_storage':
        _buildInsecureSdcardExternalStorageScreen,
    'screenshot_taskswitcher_leakage':
        _buildScreenshotTaskswitcherLeakageScreen,
    'sensitive_data_in_crash_reports': _buildSensitiveDataInCrashReportsScreen,
    'sensitive_data_in_logs': _buildSensitiveDataInLogsScreen,
    'auth_state_rollback_restore': _buildAuthStateRollbackRestoreScreen,
    'keyboard_cache_autofill_leakage': _buildKeyboardCacheAutofillLeakageScreen,
    'keychain_keystore_misuse': _buildKeychainKeystoreMisuseScreen,
    'local_security_state_integrity_tampering':
        _buildLocalSecurityStateIntegrityTamperingScreen,
    'temp_file_leftovers': _buildTempFileLeftoversScreen,
    'third_party_sdk_data_leakage': _buildThirdPartySdkDataLeakageScreen,
    'backup_archive_integrity_tampering':
        _buildBackupArchiveIntegrityTamperingScreen,
    'keychain_access_group_authorization_confusion':
        _buildKeychainAccessGroupAuthorizationConfusionScreen,
    'keychain_state_integrity_manipulation':
        _buildKeychainStateIntegrityManipulationScreen,
    'sensitive_data_in_memory': _buildSensitiveDataInMemoryScreen,
    'hardcoded_keys_ivs': _buildHardcodedKeysIvsScreen,
    'weak_algorithms': _buildWeakAlgorithmsScreen,
    'custom_crypto_implementation': _buildCustomCryptoImplementationScreen,
    'device_secure_lock_not_enforced': _buildDeviceSecureLockNotEnforcedScreen,
    'improper_mac_verification': _buildImproperMacVerificationScreen,
    'insecure_random': _buildInsecureRandomScreen,
    'rsa_no_oaep_padding': _buildRsaNoOaepPaddingScreen,
    'unauthenticated_encryption_malleable_ciphertext':
        _buildUnauthenticatedEncryptionMalleableCiphertextScreen,
    'weak_key_derivation': _buildWeakKeyDerivationScreen,
    'improper_signature_verification':
        _buildImproperSignatureVerificationScreen,
    'developer_backdoor': _buildDeveloperBackdoorScreen,
    'username_enumeration': _buildUsernameEnumerationScreen,
    'weak_password_policy': _buildWeakPasswordPolicyScreen,
    'client_side_only_authorization': _buildClientSideOnlyAuthorizationScreen,
    'cross_app_otp_credential_leak': _buildCrossAppOtpCredentialLeakScreen,
    'deeplink_authentication_bypass': _buildDeeplinkAuthenticationBypassScreen,
    'insecure_biometric_prompt': _buildInsecureBiometricPromptScreen,
    'insecure_credential_manager': _buildInsecureCredentialManagerScreen,
    'insecure_password_reset_token': _buildInsecurePasswordResetTokenScreen,
    'jwt_vulnerabilities': _buildJwtVulnerabilitiesScreen,
    'multi_account_isolation_failure': _buildMultiAccountIsolationFailureScreen,
    'passkey_credential_exfiltration':
        _buildPasskeyCredentialExfiltrationScreen,
    'passkey_credential_management_authz':
        _buildPasskeyCredentialManagementAuthzScreen,
    'passkey_fallback_downgrade': _buildPasskeyFallbackDowngradeScreen,
    'passkey_session_fixation': _buildPasskeySessionFixationScreen,
    'passkey_weak_attestation': _buildPasskeyWeakAttestationScreen,
    'weak_session_management': _buildWeakSessionManagementScreen,
    'biometric_authorization_not_bound':
        _buildBiometricAuthorizationNotBoundScreen,
    'credential_provider_release_authorization':
        _buildCredentialProviderReleaseAuthorizationScreen,
    'identity_credential_presentation_binding':
        _buildIdentityCredentialPresentationBindingScreen,
    'oauth_misconfiguration': _buildOauthMisconfigurationScreen,
    'passkey_assertion_replay_signcount':
        _buildPasskeyAssertionReplaySigncountScreen,
    'passkey_challenge_reuse': _buildPasskeyChallengeReuseScreen,
    'passkey_origin_binding_bypass': _buildPasskeyOriginBindingBypassScreen,
    'passkey_stepup_auth_bypass': _buildPasskeyStepupAuthBypassScreen,
    'passkey_thirdparty_pairing_authz':
        _buildPasskeyThirdpartyPairingAuthzScreen,
    'passkey_user_verification_bypass':
        _buildPasskeyUserVerificationBypassScreen,
    'cleartext_traffic_allowed': _buildCleartextTrafficAllowedScreen,
    'accept_all_trust_manager': _buildAcceptAllTrustManagerScreen,
    'insecure_webview_networking': _buildInsecureWebviewNetworkingScreen,
    'weak_tls_config': _buildWeakTlsConfigScreen,
    'ssl_pinning_bypass': _buildSslPinningBypassScreen,
    'activity_alias_exposure': _buildActivityAliasExposureScreen,
    'missing_flag_secure': _buildMissingFlagSecureScreen,
    'over_privileged_permissions': _buildOverPrivilegedPermissionsScreen,
    'photo_picker_over_access': _buildPhotoPickerOverAccessScreen,
    'predictive_back_leakage': _buildPredictiveBackLeakageScreen,
    'push_notification_leakage': _buildPushNotificationLeakageScreen,
    'qr_url_no_validation': _buildQrUrlNoValidationScreen,
    'app_clip_invocation_injection': _buildAppClipInvocationInjectionScreen,
    'background_activity_launch_abuse':
        _buildBackgroundActivityLaunchAbuseScreen,
    'clipboard_unauthorized_write_integrity':
        _buildClipboardUnauthorizedWriteIntegrityScreen,
    'clipdata_uri_grant_leakage': _buildClipdataUriGrantLeakageScreen,
    'contentprovider_filename_path_traversal':
        _buildContentproviderFilenamePathTraversalScreen,
    'custom_signature_permission_squatting':
        _buildCustomSignaturePermissionSquattingScreen,
    'custom_url_scheme_authorization': _buildCustomUrlSchemeAuthorizationScreen,
    'deeplink_to_webview_navigation': _buildDeeplinkToWebviewNavigationScreen,
    'deeplink_url_scheme_hijack': _buildDeeplinkUrlSchemeHijackScreen,
    'default_role_holder_confusion': _buildDefaultRoleHolderConfusionScreen,
    'document_picker_trusted_file_confusion':
        _buildDocumentPickerTrustedFileConfusionScreen,
    'dynamic_broadcast_receiver_exposure':
        _buildDynamicBroadcastReceiverExposureScreen,
    'exported_android_components': _buildExportedAndroidComponentsScreen,
    'exported_component_arbitrary_url_activity':
        _buildExportedComponentArbitraryUrlActivityScreen,
    'exported_component_state_manipulation':
        _buildExportedComponentStateManipulationScreen,
    'handoff_useractivity_injection': _buildHandoffUseractivityInjectionScreen,
    'implicit_intent_sensitive_data': _buildImplicitIntentSensitiveDataScreen,
    'inapp_browser_ui_spoofing': _buildInappBrowserUiSpoofingScreen,
    'incoming_call_metadata_missing_authorization':
        _buildIncomingCallMetadataMissingAuthorizationScreen,
    'notification_action_authorization_bypass':
        _buildNotificationActionAuthorizationBypassScreen,
    'notification_listener_authorization_bypass':
        _buildNotificationListenerAuthorizationBypassScreen,
    'ordered_broadcast_result_injection':
        _buildOrderedBroadcastResultInjectionScreen,
    'overlay_phishing': _buildOverlayPhishingScreen,
    'platform_version_security_fallback':
        _buildPlatformVersionSecurityFallbackScreen,
    'qr_code_injection': _buildQrCodeInjectionScreen,
    'ssrf_url_media_handler': _buildSsrfUrlMediaHandlerScreen,
    'tapjacking': _buildTapjackingScreen,
    'accessibility_service_privilege_abuse':
        _buildAccessibilityServicePrivilegeAbuseScreen,
    'activity_task_stack_hijacking': _buildActivityTaskStackHijackingScreen,
    'android_capability_composition_chain':
        _buildAndroidCapabilityCompositionChainScreen,
    'app_intent_parameter_authorization':
        _buildAppIntentParameterAuthorizationScreen,
    'authorization_by_mutable_resource_state':
        _buildAuthorizationByMutableResourceStateScreen,
    'clipboard_to_privileged_action_injection':
        _buildClipboardToPrivilegedActionInjectionScreen,
    'confused_deputy_intent_validation':
        _buildConfusedDeputyIntentValidationScreen,
    'contacts_provider_blind_sqli_oracle':
        _buildContactsProviderBlindSqliOracleScreen,
    'content_provider_sql_injection': _buildContentProviderSqlInjectionScreen,
    'content_uri_resolver_confused_deputy':
        _buildContentUriResolverConfusedDeputyScreen,
    'cross_app_scripting': _buildCrossAppScriptingScreen,
    'cross_profile_data_capability_leakage':
        _buildCrossProfileDataCapabilityLeakageScreen,
    'dynamic_code_loading_rce': _buildDynamicCodeLoadingRceScreen,
    'file_descriptor_capability_leakage':
        _buildFileDescriptorCapabilityLeakageScreen,
    'fileprovider_path_traversal': _buildFileproviderPathTraversalScreen,
    'grant_uri_permission_abuse': _buildGrantUriPermissionAbuseScreen,
    'insecure_webview': _buildInsecureWebviewScreen,
    'intent_arg_injection_rce': _buildIntentArgInjectionRceScreen,
    'intent_redirection': _buildIntentRedirectionScreen,
    'ios_capability_composition_chain':
        _buildIosCapabilityCompositionChainScreen,
    'pending_intent_hijacking': _buildPendingIntentHijackingScreen,
    'pendingintent_provenance_confusion':
        _buildPendingintentProvenanceConfusionScreen,
    'persistable_uri_grant_abuse': _buildPersistableUriGrantAbuseScreen,
    'privileged_service_binding_exposure':
        _buildPrivilegedServiceBindingExposureScreen,
    'proximity_transfer_unsafe_parsing':
        _buildProximityTransferUnsafeParsingScreen,
    'remoteviews_widget_action_injection':
        _buildRemoteviewsWidgetActionInjectionScreen,
    'shortcuts_path_symlink_sandbox_escape':
        _buildShortcutsPathSymlinkSandboxEscapeScreen,
    'system_surface_privileged_appintent_exposure':
        _buildSystemSurfacePrivilegedAppintentExposureScreen,
    'telephony_capability_abuse': _buildTelephonyCapabilityAbuseScreen,
    'unauthenticated_local_loopback_service':
        _buildUnauthenticatedLocalLoopbackServiceScreen,
    'universal_link_aasa_confusion': _buildUniversalLinkAasaConfusionScreen,
    'wkwebview_untrusted_url_local_file':
        _buildWkwebviewUntrustedUrlLocalFileScreen,
    'zero_click_call_media_parse_sink': _buildZeroClickCallMediaParseSinkScreen,
    'zip_path_traversal': _buildZipPathTraversalScreen,
    'debuggable_release_build': _buildDebuggableReleaseBuildScreen,
    'no_obfuscation': _buildNoObfuscationScreen,
    'verbose_error_handling': _buildVerboseErrorHandlingScreen,
    'vulnerable_dependencies': _buildVulnerableDependenciesScreen,
    'native_code_memory_bugs': _buildNativeCodeMemoryBugsScreen,
    'app_attestation_absent': _buildAppAttestationAbsentScreen,
    'device_attestation_absent': _buildDeviceAttestationAbsentScreen,
    'emulator_detection_bypass': _buildEmulatorDetectionBypassScreen,
    'malware_detection_absent': _buildMalwareDetectionAbsentScreen,
    'root_jailbreak_detection_bypass': _buildRootJailbreakDetectionBypassScreen,
    'virtualization_detection_absent':
        _buildVirtualizationDetectionAbsentScreen,
    'anti_debugging_bypass': _buildAntiDebuggingBypassScreen,
    'anti_tampering_integrity_bypass': _buildAntiTamperingIntegrityBypassScreen,
    'frida_detection_bypass': _buildFridaDetectionBypassScreen,
    'toctou_race_condition': _buildToctouRaceConditionScreen,
    'sbom_missing_or_stale': _buildSbomMissingOrStaleScreen,
    'typosquatted_dependency': _buildTyposquattedDependencyScreen,
    'insecure_firebase_cloud_config': _buildInsecureFirebaseCloudConfigScreen,
    'malicious_third_party_sdk': _buildMaliciousThirdPartySdkScreen,
    'unsigned_unverified_build_artifact':
        _buildUnsignedUnverifiedBuildArtifactScreen,
    'dependency_confusion': _buildDependencyConfusionScreen,
    'sdk_exported_component_redirection':
        _buildSdkExportedComponentRedirectionScreen,
    'silent_sdk_auto_update': _buildSilentSdkAutoUpdateScreen,
    'installed_app_enumeration': _buildInstalledAppEnumerationScreen,
    'missing_consent_before_data_access':
        _buildMissingConsentBeforeDataAccessScreen,
    'no_tracking_transparency_prompt': _buildNoTrackingTransparencyPromptScreen,
    'assistant_locked_device_capability_abuse':
        _buildAssistantLockedDeviceCapabilityAbuseScreen,
    'cross_app_browser_history_access':
        _buildCrossAppBrowserHistoryAccessScreen,
    'lock_state_confusion_data_exposure':
        _buildLockStateConfusionDataExposureScreen,
    'notification_alternate_surface_disclosure':
        _buildNotificationAlternateSurfaceDisclosureScreen,
    'pii_in_analytics_events': _buildPiiInAnalyticsEventsScreen,
    'privacy_control_alternate_path_bypass':
        _buildPrivacyControlAlternatePathBypassScreen,
    'deeplink_regex_dos': _buildDeeplinkRegexDosScreen,
    'unsafe_media_decoding': _buildUnsafeMediaDecodingScreen,
    'unvalidated_intent_extras': _buildUnvalidatedIntentExtrasScreen,
    'protected_data_access_via_input_validation':
        _buildProtectedDataAccessViaInputValidationScreen,
    'unsafe_deserialization': _buildUnsafeDeserializationScreen,
    'hardcoded_llm_api_keys': _buildHardcodedLlmApiKeysScreen,
    'prompt_injection_direct': _buildPromptInjectionDirectScreen,
    'system_prompt_leakage': _buildSystemPromptLeakageScreen,
    'unbounded_ai_resource_consumption':
        _buildUnboundedAiResourceConsumptionScreen,
    'excessive_agent_agency': _buildExcessiveAgentAgencyScreen,
    'hidden_context_exposure': _buildHiddenContextExposureScreen,
    'insecure_ondevice_model_storage': _buildInsecureOndeviceModelStorageScreen,
    'insecure_output_handling': _buildInsecureOutputHandlingScreen,
    'ondevice_model_extraction': _buildOndeviceModelExtractionScreen,
    'prompt_injection_indirect': _buildPromptInjectionIndirectScreen,
    'unicode_invisible_prompt_injection':
        _buildUnicodeInvisiblePromptInjectionScreen,
    'unverified_model_supply_chain': _buildUnverifiedModelSupplyChainScreen,
    'rag_vector_store_poisoning': _buildRagVectorStorePoisoningScreen,
    'agent_tool_confused_deputy': _buildAgentToolConfusedDeputyScreen,
    'agent_memory_poisoning': _buildAgentMemoryPoisoningScreen,
    'agent_recovery_loop_weaponization':
        _buildAgentRecoveryLoopWeaponizationScreen,
    'agent_state_toctou_swap': _buildAgentStateToctouSwapScreen,
    'gui_agent_action_rebinding': _buildGuiAgentActionRebindingScreen,
    'insecure_inter_agent_comms': _buildInsecureInterAgentCommsScreen,
    'mcp_capability_attestation_absent':
        _buildMcpCapabilityAttestationAbsentScreen,
    'mcp_open_url_arbitrary_intent': _buildMcpOpenUrlArbitraryIntentScreen,
    'mcp_tool_poisoning': _buildMcpToolPoisoningScreen,
    'ai_output_to_intent_url': _buildAiOutputToIntentUrlScreen,
    'untrusted_mobile_input_to_llm': _buildUntrustedMobileInputToLlmScreen,
    'accessibility_tree_prompt_injection':
        _buildAccessibilityTreePromptInjectionScreen,
    'ai_output_command_tool_injection':
        _buildAiOutputCommandToolInjectionScreen,
    'ai_output_to_webview_xss': _buildAiOutputToWebviewXssScreen,
    'webview_safe_browsing_disabled': _buildWebviewSafeBrowsingDisabledScreen,
    'embedded_miniapp_secret_exposure':
        _buildEmbeddedMiniappSecretExposureScreen,
    'exported_broadcast_receiver_spoof':
        _buildExportedBroadcastReceiverSpoofScreen,
    'qr_nfc_to_privileged_action': _buildQrNfcToPrivilegedActionScreen,
    'webview_cleartext_mixed_content_downgrade':
        _buildWebviewCleartextMixedContentDowngradeScreen,
    'webview_remote_debugging_enabled':
        _buildWebviewRemoteDebuggingEnabledScreen,
    'crossorigin_iframe_to_native_bridge':
        _buildCrossoriginIframeToNativeBridgeScreen,
    'js_bridge_callback_id_injection': _buildJsBridgeCallbackIdInjectionScreen,
    'js_bridge_exposes_privileged_api':
        _buildJsBridgeExposesPrivilegedApiScreen,
    'provider_metadata_to_filesystem_traversal':
        _buildProviderMetadataToFilesystemTraversalScreen,
    'shared_webview_miniapp_isolation':
        _buildSharedWebviewMiniappIsolationScreen,
    'webview_js_injection_ssl_bypass': _buildWebviewJsInjectionSslBypassScreen,
    'webview_origin_confusion_ipc': _buildWebviewOriginConfusionIpcScreen,
    'webview_sop_csp_disabled': _buildWebviewSopCspDisabledScreen,
    'webview_url_loading_policy_confusion':
        _buildWebviewUrlLoadingPolicyConfusionScreen,
    'app_group_shared_container_amplification':
        _buildAppGroupSharedContainerAmplificationScreen,
    'assist_screen_context_ai_exposure':
        _buildAssistScreenContextAiExposureScreen,
    'companion_device_pairing_confusion':
        _buildCompanionDevicePairingConfusionScreen,
    'custom_keyboard_input_interception':
        _buildCustomKeyboardInputInterceptionScreen,
    'extension_activation_input_confusion':
        _buildExtensionActivationInputConfusionScreen,
    'lockscreen_control_action_authorization':
        _buildLockscreenControlActionAuthorizationScreen,
    'notification_intelligence_ai_processing':
        _buildNotificationIntelligenceAiProcessingScreen,
    'device_policy_mdm_capability_abuse':
        _buildDevicePolicyMdmCapabilityAbuseScreen,
    'mediaprojection_screencapture_authorization_bypass':
        _buildMediaprojectionScreencaptureAuthorizationBypassScreen,
    'privileged_input_provider_injection':
        _buildPrivilegedInputProviderInjectionScreen,
    'privileged_provider_activation_abuse':
        _buildPrivilegedProviderActivationAbuseScreen,
    'vpn_provider_trust_anchor_abuse': _buildVpnProviderTrustAnchorAbuseScreen,
  };

  static Widget _buildClipboardLeakageScreen(BuildContext context) =>
      const ClipboardLeakageScreen();
  static Widget _buildInsecureBackupsScreen(BuildContext context) =>
      const InsecureBackupsScreen();
  static Widget _buildInsecureLocalStorageScreen(BuildContext context) =>
      const InsecureLocalStorageScreen();
  static Widget _buildInsecureSdcardExternalStorageScreen(
    BuildContext context,
  ) => const InsecureSdcardExternalStorageScreen();
  static Widget _buildScreenshotTaskswitcherLeakageScreen(
    BuildContext context,
  ) => const ScreenshotTaskswitcherLeakageScreen();
  static Widget _buildSensitiveDataInCrashReportsScreen(BuildContext context) =>
      const SensitiveDataInCrashReportsScreen();
  static Widget _buildSensitiveDataInLogsScreen(BuildContext context) =>
      const SensitiveDataInLogsScreen();
  static Widget _buildAuthStateRollbackRestoreScreen(BuildContext context) =>
      const AuthStateRollbackRestoreScreen();
  static Widget _buildKeyboardCacheAutofillLeakageScreen(
    BuildContext context,
  ) => const KeyboardCacheAutofillLeakageScreen();
  static Widget _buildKeychainKeystoreMisuseScreen(BuildContext context) =>
      const KeychainKeystoreMisuseScreen();
  static Widget _buildLocalSecurityStateIntegrityTamperingScreen(
    BuildContext context,
  ) => const LocalSecurityStateIntegrityTamperingScreen();
  static Widget _buildTempFileLeftoversScreen(BuildContext context) =>
      const TempFileLeftoversScreen();
  static Widget _buildThirdPartySdkDataLeakageScreen(BuildContext context) =>
      const ThirdPartySdkDataLeakageScreen();
  static Widget _buildBackupArchiveIntegrityTamperingScreen(
    BuildContext context,
  ) => const BackupArchiveIntegrityTamperingScreen();
  static Widget _buildKeychainAccessGroupAuthorizationConfusionScreen(
    BuildContext context,
  ) => const KeychainAccessGroupAuthorizationConfusionScreen();
  static Widget _buildKeychainStateIntegrityManipulationScreen(
    BuildContext context,
  ) => const KeychainStateIntegrityManipulationScreen();
  static Widget _buildSensitiveDataInMemoryScreen(BuildContext context) =>
      const SensitiveDataInMemoryScreen();
  static Widget _buildHardcodedKeysIvsScreen(BuildContext context) =>
      const HardcodedKeysIvsScreen();
  static Widget _buildWeakAlgorithmsScreen(BuildContext context) =>
      const WeakAlgorithmsScreen();
  static Widget _buildCustomCryptoImplementationScreen(BuildContext context) =>
      const CustomCryptoImplementationScreen();
  static Widget _buildDeviceSecureLockNotEnforcedScreen(BuildContext context) =>
      const DeviceSecureLockNotEnforcedScreen();
  static Widget _buildImproperMacVerificationScreen(BuildContext context) =>
      const ImproperMacVerificationScreen();
  static Widget _buildInsecureRandomScreen(BuildContext context) =>
      const InsecureRandomScreen();
  static Widget _buildRsaNoOaepPaddingScreen(BuildContext context) =>
      const RsaNoOaepPaddingScreen();
  static Widget _buildUnauthenticatedEncryptionMalleableCiphertextScreen(
    BuildContext context,
  ) => const UnauthenticatedEncryptionMalleableCiphertextScreen();
  static Widget _buildWeakKeyDerivationScreen(BuildContext context) =>
      const WeakKeyDerivationScreen();
  static Widget _buildImproperSignatureVerificationScreen(
    BuildContext context,
  ) => const ImproperSignatureVerificationScreen();
  static Widget _buildDeveloperBackdoorScreen(BuildContext context) =>
      const DeveloperBackdoorScreen();
  static Widget _buildUsernameEnumerationScreen(BuildContext context) =>
      const UsernameEnumerationScreen();
  static Widget _buildWeakPasswordPolicyScreen(BuildContext context) =>
      const WeakPasswordPolicyScreen();
  static Widget _buildClientSideOnlyAuthorizationScreen(BuildContext context) =>
      const ClientSideOnlyAuthorizationScreen();
  static Widget _buildCrossAppOtpCredentialLeakScreen(BuildContext context) =>
      const CrossAppOtpCredentialLeakScreen();
  static Widget _buildDeeplinkAuthenticationBypassScreen(
    BuildContext context,
  ) => const DeeplinkAuthenticationBypassScreen();
  static Widget _buildInsecureBiometricPromptScreen(BuildContext context) =>
      const InsecureBiometricPromptScreen();
  static Widget _buildInsecureCredentialManagerScreen(BuildContext context) =>
      const InsecureCredentialManagerScreen();
  static Widget _buildInsecurePasswordResetTokenScreen(BuildContext context) =>
      const InsecurePasswordResetTokenScreen();
  static Widget _buildJwtVulnerabilitiesScreen(BuildContext context) =>
      const JwtVulnerabilitiesScreen();
  static Widget _buildMultiAccountIsolationFailureScreen(
    BuildContext context,
  ) => const MultiAccountIsolationFailureScreen();
  static Widget _buildPasskeyCredentialExfiltrationScreen(
    BuildContext context,
  ) => const PasskeyCredentialExfiltrationScreen();
  static Widget _buildPasskeyCredentialManagementAuthzScreen(
    BuildContext context,
  ) => const PasskeyCredentialManagementAuthzScreen();
  static Widget _buildPasskeyFallbackDowngradeScreen(BuildContext context) =>
      const PasskeyFallbackDowngradeScreen();
  static Widget _buildPasskeySessionFixationScreen(BuildContext context) =>
      const PasskeySessionFixationScreen();
  static Widget _buildPasskeyWeakAttestationScreen(BuildContext context) =>
      const PasskeyWeakAttestationScreen();
  static Widget _buildWeakSessionManagementScreen(BuildContext context) =>
      const WeakSessionManagementScreen();
  static Widget _buildBiometricAuthorizationNotBoundScreen(
    BuildContext context,
  ) => const BiometricAuthorizationNotBoundScreen();
  static Widget _buildCredentialProviderReleaseAuthorizationScreen(
    BuildContext context,
  ) => const CredentialProviderReleaseAuthorizationScreen();
  static Widget _buildIdentityCredentialPresentationBindingScreen(
    BuildContext context,
  ) => const IdentityCredentialPresentationBindingScreen();
  static Widget _buildOauthMisconfigurationScreen(BuildContext context) =>
      const OauthMisconfigurationScreen();
  static Widget _buildPasskeyAssertionReplaySigncountScreen(
    BuildContext context,
  ) => const PasskeyAssertionReplaySigncountScreen();
  static Widget _buildPasskeyChallengeReuseScreen(BuildContext context) =>
      const PasskeyChallengeReuseScreen();
  static Widget _buildPasskeyOriginBindingBypassScreen(BuildContext context) =>
      const PasskeyOriginBindingBypassScreen();
  static Widget _buildPasskeyStepupAuthBypassScreen(BuildContext context) =>
      const PasskeyStepupAuthBypassScreen();
  static Widget _buildPasskeyThirdpartyPairingAuthzScreen(
    BuildContext context,
  ) => const PasskeyThirdpartyPairingAuthzScreen();
  static Widget _buildPasskeyUserVerificationBypassScreen(
    BuildContext context,
  ) => const PasskeyUserVerificationBypassScreen();
  static Widget _buildCleartextTrafficAllowedScreen(BuildContext context) =>
      const CleartextTrafficAllowedScreen();
  static Widget _buildAcceptAllTrustManagerScreen(BuildContext context) =>
      const AcceptAllTrustManagerScreen();
  static Widget _buildInsecureWebviewNetworkingScreen(BuildContext context) =>
      const InsecureWebviewNetworkingScreen();
  static Widget _buildWeakTlsConfigScreen(BuildContext context) =>
      const WeakTlsConfigScreen();
  static Widget _buildSslPinningBypassScreen(BuildContext context) =>
      const SslPinningBypassScreen();
  static Widget _buildActivityAliasExposureScreen(BuildContext context) =>
      const ActivityAliasExposureScreen();
  static Widget _buildMissingFlagSecureScreen(BuildContext context) =>
      const MissingFlagSecureScreen();
  static Widget _buildOverPrivilegedPermissionsScreen(BuildContext context) =>
      const OverPrivilegedPermissionsScreen();
  static Widget _buildPhotoPickerOverAccessScreen(BuildContext context) =>
      const PhotoPickerOverAccessScreen();
  static Widget _buildPredictiveBackLeakageScreen(BuildContext context) =>
      const PredictiveBackLeakageScreen();
  static Widget _buildPushNotificationLeakageScreen(BuildContext context) =>
      const PushNotificationLeakageScreen();
  static Widget _buildQrUrlNoValidationScreen(BuildContext context) =>
      const QrUrlNoValidationScreen();
  static Widget _buildAppClipInvocationInjectionScreen(BuildContext context) =>
      const AppClipInvocationInjectionScreen();
  static Widget _buildBackgroundActivityLaunchAbuseScreen(
    BuildContext context,
  ) => const BackgroundActivityLaunchAbuseScreen();
  static Widget _buildClipboardUnauthorizedWriteIntegrityScreen(
    BuildContext context,
  ) => const ClipboardUnauthorizedWriteIntegrityScreen();
  static Widget _buildClipdataUriGrantLeakageScreen(BuildContext context) =>
      const ClipdataUriGrantLeakageScreen();
  static Widget _buildContentproviderFilenamePathTraversalScreen(
    BuildContext context,
  ) => const ContentproviderFilenamePathTraversalScreen();
  static Widget _buildCustomSignaturePermissionSquattingScreen(
    BuildContext context,
  ) => const CustomSignaturePermissionSquattingScreen();
  static Widget _buildCustomUrlSchemeAuthorizationScreen(
    BuildContext context,
  ) => const CustomUrlSchemeAuthorizationScreen();
  static Widget _buildDeeplinkToWebviewNavigationScreen(BuildContext context) =>
      const DeeplinkToWebviewNavigationScreen();
  static Widget _buildDeeplinkUrlSchemeHijackScreen(BuildContext context) =>
      const DeeplinkUrlSchemeHijackScreen();
  static Widget _buildDefaultRoleHolderConfusionScreen(BuildContext context) =>
      const DefaultRoleHolderConfusionScreen();
  static Widget _buildDocumentPickerTrustedFileConfusionScreen(
    BuildContext context,
  ) => const DocumentPickerTrustedFileConfusionScreen();
  static Widget _buildDynamicBroadcastReceiverExposureScreen(
    BuildContext context,
  ) => const DynamicBroadcastReceiverExposureScreen();
  static Widget _buildExportedAndroidComponentsScreen(BuildContext context) =>
      const ExportedAndroidComponentsScreen();
  static Widget _buildExportedComponentArbitraryUrlActivityScreen(
    BuildContext context,
  ) => const ExportedComponentArbitraryUrlActivityScreen();
  static Widget _buildExportedComponentStateManipulationScreen(
    BuildContext context,
  ) => const ExportedComponentStateManipulationScreen();
  static Widget _buildHandoffUseractivityInjectionScreen(
    BuildContext context,
  ) => const HandoffUseractivityInjectionScreen();
  static Widget _buildImplicitIntentSensitiveDataScreen(BuildContext context) =>
      const ImplicitIntentSensitiveDataScreen();
  static Widget _buildInappBrowserUiSpoofingScreen(BuildContext context) =>
      const InappBrowserUiSpoofingScreen();
  static Widget _buildIncomingCallMetadataMissingAuthorizationScreen(
    BuildContext context,
  ) => const IncomingCallMetadataMissingAuthorizationScreen();
  static Widget _buildNotificationActionAuthorizationBypassScreen(
    BuildContext context,
  ) => const NotificationActionAuthorizationBypassScreen();
  static Widget _buildNotificationListenerAuthorizationBypassScreen(
    BuildContext context,
  ) => const NotificationListenerAuthorizationBypassScreen();
  static Widget _buildOrderedBroadcastResultInjectionScreen(
    BuildContext context,
  ) => const OrderedBroadcastResultInjectionScreen();
  static Widget _buildOverlayPhishingScreen(BuildContext context) =>
      const OverlayPhishingScreen();
  static Widget _buildPlatformVersionSecurityFallbackScreen(
    BuildContext context,
  ) => const PlatformVersionSecurityFallbackScreen();
  static Widget _buildQrCodeInjectionScreen(BuildContext context) =>
      const QrCodeInjectionScreen();
  static Widget _buildSsrfUrlMediaHandlerScreen(BuildContext context) =>
      const SsrfUrlMediaHandlerScreen();
  static Widget _buildTapjackingScreen(BuildContext context) =>
      const TapjackingScreen();
  static Widget _buildAccessibilityServicePrivilegeAbuseScreen(
    BuildContext context,
  ) => const AccessibilityServicePrivilegeAbuseScreen();
  static Widget _buildActivityTaskStackHijackingScreen(BuildContext context) =>
      const ActivityTaskStackHijackingScreen();
  static Widget _buildAndroidCapabilityCompositionChainScreen(
    BuildContext context,
  ) => const AndroidCapabilityCompositionChainScreen();
  static Widget _buildAppIntentParameterAuthorizationScreen(
    BuildContext context,
  ) => const AppIntentParameterAuthorizationScreen();
  static Widget _buildAuthorizationByMutableResourceStateScreen(
    BuildContext context,
  ) => const AuthorizationByMutableResourceStateScreen();
  static Widget _buildClipboardToPrivilegedActionInjectionScreen(
    BuildContext context,
  ) => const ClipboardToPrivilegedActionInjectionScreen();
  static Widget _buildConfusedDeputyIntentValidationScreen(
    BuildContext context,
  ) => const ConfusedDeputyIntentValidationScreen();
  static Widget _buildContactsProviderBlindSqliOracleScreen(
    BuildContext context,
  ) => const ContactsProviderBlindSqliOracleScreen();
  static Widget _buildContentProviderSqlInjectionScreen(BuildContext context) =>
      const ContentProviderSqlInjectionScreen();
  static Widget _buildContentUriResolverConfusedDeputyScreen(
    BuildContext context,
  ) => const ContentUriResolverConfusedDeputyScreen();
  static Widget _buildCrossAppScriptingScreen(BuildContext context) =>
      const CrossAppScriptingScreen();
  static Widget _buildCrossProfileDataCapabilityLeakageScreen(
    BuildContext context,
  ) => const CrossProfileDataCapabilityLeakageScreen();
  static Widget _buildDynamicCodeLoadingRceScreen(BuildContext context) =>
      const DynamicCodeLoadingRceScreen();
  static Widget _buildFileDescriptorCapabilityLeakageScreen(
    BuildContext context,
  ) => const FileDescriptorCapabilityLeakageScreen();
  static Widget _buildFileproviderPathTraversalScreen(BuildContext context) =>
      const FileproviderPathTraversalScreen();
  static Widget _buildGrantUriPermissionAbuseScreen(BuildContext context) =>
      const GrantUriPermissionAbuseScreen();
  static Widget _buildInsecureWebviewScreen(BuildContext context) =>
      const InsecureWebviewScreen();
  static Widget _buildIntentArgInjectionRceScreen(BuildContext context) =>
      const IntentArgInjectionRceScreen();
  static Widget _buildIntentRedirectionScreen(BuildContext context) =>
      const IntentRedirectionScreen();
  static Widget _buildIosCapabilityCompositionChainScreen(
    BuildContext context,
  ) => const IosCapabilityCompositionChainScreen();
  static Widget _buildPendingIntentHijackingScreen(BuildContext context) =>
      const PendingIntentHijackingScreen();
  static Widget _buildPendingintentProvenanceConfusionScreen(
    BuildContext context,
  ) => const PendingintentProvenanceConfusionScreen();
  static Widget _buildPersistableUriGrantAbuseScreen(BuildContext context) =>
      const PersistableUriGrantAbuseScreen();
  static Widget _buildPrivilegedServiceBindingExposureScreen(
    BuildContext context,
  ) => const PrivilegedServiceBindingExposureScreen();
  static Widget _buildProximityTransferUnsafeParsingScreen(
    BuildContext context,
  ) => const ProximityTransferUnsafeParsingScreen();
  static Widget _buildRemoteviewsWidgetActionInjectionScreen(
    BuildContext context,
  ) => const RemoteviewsWidgetActionInjectionScreen();
  static Widget _buildShortcutsPathSymlinkSandboxEscapeScreen(
    BuildContext context,
  ) => const ShortcutsPathSymlinkSandboxEscapeScreen();
  static Widget _buildSystemSurfacePrivilegedAppintentExposureScreen(
    BuildContext context,
  ) => const SystemSurfacePrivilegedAppintentExposureScreen();
  static Widget _buildTelephonyCapabilityAbuseScreen(BuildContext context) =>
      const TelephonyCapabilityAbuseScreen();
  static Widget _buildUnauthenticatedLocalLoopbackServiceScreen(
    BuildContext context,
  ) => const UnauthenticatedLocalLoopbackServiceScreen();
  static Widget _buildUniversalLinkAasaConfusionScreen(BuildContext context) =>
      const UniversalLinkAasaConfusionScreen();
  static Widget _buildWkwebviewUntrustedUrlLocalFileScreen(
    BuildContext context,
  ) => const WkwebviewUntrustedUrlLocalFileScreen();
  static Widget _buildZeroClickCallMediaParseSinkScreen(BuildContext context) =>
      const ZeroClickCallMediaParseSinkScreen();
  static Widget _buildZipPathTraversalScreen(BuildContext context) =>
      const ZipPathTraversalScreen();
  static Widget _buildDebuggableReleaseBuildScreen(BuildContext context) =>
      const DebuggableReleaseBuildScreen();
  static Widget _buildNoObfuscationScreen(BuildContext context) =>
      const NoObfuscationScreen();
  static Widget _buildVerboseErrorHandlingScreen(BuildContext context) =>
      const VerboseErrorHandlingScreen();
  static Widget _buildVulnerableDependenciesScreen(BuildContext context) =>
      const VulnerableDependenciesScreen();
  static Widget _buildNativeCodeMemoryBugsScreen(BuildContext context) =>
      const NativeCodeMemoryBugsScreen();
  static Widget _buildAppAttestationAbsentScreen(BuildContext context) =>
      const AppAttestationAbsentScreen();
  static Widget _buildDeviceAttestationAbsentScreen(BuildContext context) =>
      const DeviceAttestationAbsentScreen();
  static Widget _buildEmulatorDetectionBypassScreen(BuildContext context) =>
      const EmulatorDetectionBypassScreen();
  static Widget _buildMalwareDetectionAbsentScreen(BuildContext context) =>
      const MalwareDetectionAbsentScreen();
  static Widget _buildRootJailbreakDetectionBypassScreen(
    BuildContext context,
  ) => const RootJailbreakDetectionBypassScreen();
  static Widget _buildVirtualizationDetectionAbsentScreen(
    BuildContext context,
  ) => const VirtualizationDetectionAbsentScreen();
  static Widget _buildAntiDebuggingBypassScreen(BuildContext context) =>
      const AntiDebuggingBypassScreen();
  static Widget _buildAntiTamperingIntegrityBypassScreen(
    BuildContext context,
  ) => const AntiTamperingIntegrityBypassScreen();
  static Widget _buildFridaDetectionBypassScreen(BuildContext context) =>
      const FridaDetectionBypassScreen();
  static Widget _buildToctouRaceConditionScreen(BuildContext context) =>
      const ToctouRaceConditionScreen();
  static Widget _buildSbomMissingOrStaleScreen(BuildContext context) =>
      const SbomMissingOrStaleScreen();
  static Widget _buildTyposquattedDependencyScreen(BuildContext context) =>
      const TyposquattedDependencyScreen();
  static Widget _buildInsecureFirebaseCloudConfigScreen(BuildContext context) =>
      const InsecureFirebaseCloudConfigScreen();
  static Widget _buildMaliciousThirdPartySdkScreen(BuildContext context) =>
      const MaliciousThirdPartySdkScreen();
  static Widget _buildUnsignedUnverifiedBuildArtifactScreen(
    BuildContext context,
  ) => const UnsignedUnverifiedBuildArtifactScreen();
  static Widget _buildDependencyConfusionScreen(BuildContext context) =>
      const DependencyConfusionScreen();
  static Widget _buildSdkExportedComponentRedirectionScreen(
    BuildContext context,
  ) => const SdkExportedComponentRedirectionScreen();
  static Widget _buildSilentSdkAutoUpdateScreen(BuildContext context) =>
      const SilentSdkAutoUpdateScreen();
  static Widget _buildInstalledAppEnumerationScreen(BuildContext context) =>
      const InstalledAppEnumerationScreen();
  static Widget _buildMissingConsentBeforeDataAccessScreen(
    BuildContext context,
  ) => const MissingConsentBeforeDataAccessScreen();
  static Widget _buildNoTrackingTransparencyPromptScreen(
    BuildContext context,
  ) => const NoTrackingTransparencyPromptScreen();
  static Widget _buildAssistantLockedDeviceCapabilityAbuseScreen(
    BuildContext context,
  ) => const AssistantLockedDeviceCapabilityAbuseScreen();
  static Widget _buildCrossAppBrowserHistoryAccessScreen(
    BuildContext context,
  ) => const CrossAppBrowserHistoryAccessScreen();
  static Widget _buildLockStateConfusionDataExposureScreen(
    BuildContext context,
  ) => const LockStateConfusionDataExposureScreen();
  static Widget _buildNotificationAlternateSurfaceDisclosureScreen(
    BuildContext context,
  ) => const NotificationAlternateSurfaceDisclosureScreen();
  static Widget _buildPiiInAnalyticsEventsScreen(BuildContext context) =>
      const PiiInAnalyticsEventsScreen();
  static Widget _buildPrivacyControlAlternatePathBypassScreen(
    BuildContext context,
  ) => const PrivacyControlAlternatePathBypassScreen();
  static Widget _buildDeeplinkRegexDosScreen(BuildContext context) =>
      const DeeplinkRegexDosScreen();
  static Widget _buildUnsafeMediaDecodingScreen(BuildContext context) =>
      const UnsafeMediaDecodingScreen();
  static Widget _buildUnvalidatedIntentExtrasScreen(BuildContext context) =>
      const UnvalidatedIntentExtrasScreen();
  static Widget _buildProtectedDataAccessViaInputValidationScreen(
    BuildContext context,
  ) => const ProtectedDataAccessViaInputValidationScreen();
  static Widget _buildUnsafeDeserializationScreen(BuildContext context) =>
      const UnsafeDeserializationScreen();
  static Widget _buildHardcodedLlmApiKeysScreen(BuildContext context) =>
      const HardcodedLlmApiKeysScreen();
  static Widget _buildPromptInjectionDirectScreen(BuildContext context) =>
      const PromptInjectionDirectScreen();
  static Widget _buildSystemPromptLeakageScreen(BuildContext context) =>
      const SystemPromptLeakageScreen();
  static Widget _buildUnboundedAiResourceConsumptionScreen(
    BuildContext context,
  ) => const UnboundedAiResourceConsumptionScreen();
  static Widget _buildExcessiveAgentAgencyScreen(BuildContext context) =>
      const ExcessiveAgentAgencyScreen();
  static Widget _buildHiddenContextExposureScreen(BuildContext context) =>
      const HiddenContextExposureScreen();
  static Widget _buildInsecureOndeviceModelStorageScreen(
    BuildContext context,
  ) => const InsecureOndeviceModelStorageScreen();
  static Widget _buildInsecureOutputHandlingScreen(BuildContext context) =>
      const InsecureOutputHandlingScreen();
  static Widget _buildOndeviceModelExtractionScreen(BuildContext context) =>
      const OndeviceModelExtractionScreen();
  static Widget _buildPromptInjectionIndirectScreen(BuildContext context) =>
      const PromptInjectionIndirectScreen();
  static Widget _buildUnicodeInvisiblePromptInjectionScreen(
    BuildContext context,
  ) => const UnicodeInvisiblePromptInjectionScreen();
  static Widget _buildUnverifiedModelSupplyChainScreen(BuildContext context) =>
      const UnverifiedModelSupplyChainScreen();
  static Widget _buildRagVectorStorePoisoningScreen(BuildContext context) =>
      const RagVectorStorePoisoningScreen();
  static Widget _buildAgentToolConfusedDeputyScreen(BuildContext context) =>
      const AgentToolConfusedDeputyScreen();
  static Widget _buildAgentMemoryPoisoningScreen(BuildContext context) =>
      const AgentMemoryPoisoningScreen();
  static Widget _buildAgentRecoveryLoopWeaponizationScreen(
    BuildContext context,
  ) => const AgentRecoveryLoopWeaponizationScreen();
  static Widget _buildAgentStateToctouSwapScreen(BuildContext context) =>
      const AgentStateToctouSwapScreen();
  static Widget _buildGuiAgentActionRebindingScreen(BuildContext context) =>
      const GuiAgentActionRebindingScreen();
  static Widget _buildInsecureInterAgentCommsScreen(BuildContext context) =>
      const InsecureInterAgentCommsScreen();
  static Widget _buildMcpCapabilityAttestationAbsentScreen(
    BuildContext context,
  ) => const McpCapabilityAttestationAbsentScreen();
  static Widget _buildMcpOpenUrlArbitraryIntentScreen(BuildContext context) =>
      const McpOpenUrlArbitraryIntentScreen();
  static Widget _buildMcpToolPoisoningScreen(BuildContext context) =>
      const McpToolPoisoningScreen();
  static Widget _buildAiOutputToIntentUrlScreen(BuildContext context) =>
      const AiOutputToIntentUrlScreen();
  static Widget _buildUntrustedMobileInputToLlmScreen(BuildContext context) =>
      const UntrustedMobileInputToLlmScreen();
  static Widget _buildAccessibilityTreePromptInjectionScreen(
    BuildContext context,
  ) => const AccessibilityTreePromptInjectionScreen();
  static Widget _buildAiOutputCommandToolInjectionScreen(
    BuildContext context,
  ) => const AiOutputCommandToolInjectionScreen();
  static Widget _buildAiOutputToWebviewXssScreen(BuildContext context) =>
      const AiOutputToWebviewXssScreen();
  static Widget _buildWebviewSafeBrowsingDisabledScreen(BuildContext context) =>
      const WebviewSafeBrowsingDisabledScreen();
  static Widget _buildEmbeddedMiniappSecretExposureScreen(
    BuildContext context,
  ) => const EmbeddedMiniappSecretExposureScreen();
  static Widget _buildExportedBroadcastReceiverSpoofScreen(
    BuildContext context,
  ) => const ExportedBroadcastReceiverSpoofScreen();
  static Widget _buildQrNfcToPrivilegedActionScreen(BuildContext context) =>
      const QrNfcToPrivilegedActionScreen();
  static Widget _buildWebviewCleartextMixedContentDowngradeScreen(
    BuildContext context,
  ) => const WebviewCleartextMixedContentDowngradeScreen();
  static Widget _buildWebviewRemoteDebuggingEnabledScreen(
    BuildContext context,
  ) => const WebviewRemoteDebuggingEnabledScreen();
  static Widget _buildCrossoriginIframeToNativeBridgeScreen(
    BuildContext context,
  ) => const CrossoriginIframeToNativeBridgeScreen();
  static Widget _buildJsBridgeCallbackIdInjectionScreen(BuildContext context) =>
      const JsBridgeCallbackIdInjectionScreen();
  static Widget _buildJsBridgeExposesPrivilegedApiScreen(
    BuildContext context,
  ) => const JsBridgeExposesPrivilegedApiScreen();
  static Widget _buildProviderMetadataToFilesystemTraversalScreen(
    BuildContext context,
  ) => const ProviderMetadataToFilesystemTraversalScreen();
  static Widget _buildSharedWebviewMiniappIsolationScreen(
    BuildContext context,
  ) => const SharedWebviewMiniappIsolationScreen();
  static Widget _buildWebviewJsInjectionSslBypassScreen(BuildContext context) =>
      const WebviewJsInjectionSslBypassScreen();
  static Widget _buildWebviewOriginConfusionIpcScreen(BuildContext context) =>
      const WebviewOriginConfusionIpcScreen();
  static Widget _buildWebviewSopCspDisabledScreen(BuildContext context) =>
      const WebviewSopCspDisabledScreen();
  static Widget _buildWebviewUrlLoadingPolicyConfusionScreen(
    BuildContext context,
  ) => const WebviewUrlLoadingPolicyConfusionScreen();
  static Widget _buildAppGroupSharedContainerAmplificationScreen(
    BuildContext context,
  ) => const AppGroupSharedContainerAmplificationScreen();
  static Widget _buildAssistScreenContextAiExposureScreen(
    BuildContext context,
  ) => const AssistScreenContextAiExposureScreen();
  static Widget _buildCompanionDevicePairingConfusionScreen(
    BuildContext context,
  ) => const CompanionDevicePairingConfusionScreen();
  static Widget _buildCustomKeyboardInputInterceptionScreen(
    BuildContext context,
  ) => const CustomKeyboardInputInterceptionScreen();
  static Widget _buildExtensionActivationInputConfusionScreen(
    BuildContext context,
  ) => const ExtensionActivationInputConfusionScreen();
  static Widget _buildLockscreenControlActionAuthorizationScreen(
    BuildContext context,
  ) => const LockscreenControlActionAuthorizationScreen();
  static Widget _buildNotificationIntelligenceAiProcessingScreen(
    BuildContext context,
  ) => const NotificationIntelligenceAiProcessingScreen();
  static Widget _buildDevicePolicyMdmCapabilityAbuseScreen(
    BuildContext context,
  ) => const DevicePolicyMdmCapabilityAbuseScreen();
  static Widget _buildMediaprojectionScreencaptureAuthorizationBypassScreen(
    BuildContext context,
  ) => const MediaprojectionScreencaptureAuthorizationBypassScreen();
  static Widget _buildPrivilegedInputProviderInjectionScreen(
    BuildContext context,
  ) => const PrivilegedInputProviderInjectionScreen();
  static Widget _buildPrivilegedProviderActivationAbuseScreen(
    BuildContext context,
  ) => const PrivilegedProviderActivationAbuseScreen();
  static Widget _buildVpnProviderTrustAnchorAbuseScreen(BuildContext context) =>
      const VpnProviderTrustAnchorAbuseScreen();

  /// Returns the screen builder for [vulnId].
  static ScreenBuilder screenFor(String vulnId) =>
      _screens[vulnId] ?? _missing(vulnId);

  static ScreenBuilder _missing(String vulnId) =>
      (context) => Scaffold(
        appBar: AppBar(title: const Text('Not found')),
        body: Center(child: Text('No screen registered for $vulnId')),
      );

  /// All registered ids (used by the master integration test).
  static List<String> get registeredIds => _screens.keys.toList();
}
